
INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,CH_ID_METODO, CH_EST_REG,VC_ID_USUARIO_CRE)
VALUES('DOCU','000008','EQUI','ICA0071','*','A','ESALINAS')


