
--INSERTS PARA SEGURDAD ACCESO
INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','ACC-CER-001TG','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','ACC-CMR-001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','ACC-CMR-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','ACC-CONT-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','ACC-LEC-0001TG','*','A','ESALINAS');
INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','ACC-RFID-001TG','*','A','ESALINAS');
INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','BJA-SIS-0001TG','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','BRA-ACC-0003','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','BRA-ACC-0003TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','CER-ELEC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','EXT-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','GAB-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','JBOX-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','KIT-CONTR-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','KIT-CONTR-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','KIT-LIGHT-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','KIT-SEG-0001','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SEN-ANG-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SEN-HUM-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SEN-MAG-0001','*','A','ESALINAS')
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SEN-OCU-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SEN-OCU-0001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SERV-SEG-0001TG','*','A','ESALINAS');
   INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SIR-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SIS-GRB-0002','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SIS-GRB-0002TG','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SPTE-CMR-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','SPTE-CMR-002TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000013','EQUI','TAR-ACC-0001','*','A','ESALINAS');

 --INSERTS PARA SEGURIDAD DISTRIBUCION
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','ACC-CER-001TG','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','ACC-CMR-001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','ACC-CMR-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','ACC-CONT-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','ACC-LEC-0001TG','*','A','ESALINAS');
INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','ACC-RFID-001TG','*','A','ESALINAS');
INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','BJA-SIS-0001TG','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','BRA-ACC-0003','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','BRA-ACC-0003TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','CER-ELEC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','EXT-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','GAB-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','JBOX-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','KIT-CONTR-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','KIT-CONTR-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','KIT-LIGHT-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','KIT-SEG-0001','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SEN-ANG-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SEN-HUM-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SEN-MAG-0001','*','A','ESALINAS')
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SEN-OCU-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SEN-OCU-0001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SERV-SEG-0001TG','*','A','ESALINAS');
   INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SIR-ACC-0001','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SIS-GRB-0002','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SIS-GRB-0002TG','*','A','ESALINAS');
 INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SPTE-CMR-001TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','SPTE-CMR-002TG','*','A','ESALINAS');
  INSERT INTO ENTIDAD_DET_RELACION(VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,
CH_ID_METODO,CH_EST_REG,VC_ID_USUARIO_CRE)
 VALUES('DOCU','000014','EQUI','TAR-ACC-0001','*','A','ESALINAS');