
INSERT INTO ENTIDAD_DET_RELACION (VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,CH_ID_METODO,VC_ID_USUARIO_CRE) VALUES
('DOCU', '000013','EQUI','LEC-RFID-0001','*','ESALINAS');

INSERT INTO ENTIDAD_DET_RELACION (VC_ID_ENTIDAD_P,VC_ID_VALOR_P,VC_ID_ENTIDAD_S,VC_ID_VALOR_S,CH_ID_METODO,VC_ID_USUARIO_CRE) VALUES
('DOCU', '000014','EQUI','LEC-RFID-0001','*','ESALINAS')
