
--ACTUALIZACION DE DATA PARA LA TABLA ENTIDAD DETALLE 
 UPDATE ENTIDAD_DET
SET  VC_VALOR_CADENA3='AIO SYSTEMS'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'CONT-ACC-002'

 UPDATE ENTIDAD_DET
SET  VC_VALOR_CADENA3='AIO SYSTEMS'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'CONT-ACC-003'

UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA1 = 'SENSOR CONTACTO EN LA PUERTA PRINCIPAL', VC_VALOR_CADENA3='AIO SYSTEMS',VC_VALOR_CADENA4 = 'MAGNETICO SENSOR'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'SEN-MAG-0001';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA1 = 'DETECTORES DE HUMO', VC_VALOR_CADENA3='AIO Systems',VC_VALOR_CADENA4 = 'SMOKE DETECTOR'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'SEN-HUM-0001';
UPDATE ENTIDAD_DET
SET  VC_VALOR_CADENA3='AIO Systems',VC_VALOR_CADENA4 = 'FLOOD DETECTOR'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'SEN-ANG-0001'
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA1 = 'EXTINTOR + CAJA OUTDOOR', VC_VALOR_CADENA3='ISFE',VC_VALOR_CADENA4 = 'C02'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'EXT-ACC-0001';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA1 = 'CERRADURA ELECTRICA', VC_VALOR_CADENA3='CANTOL',VC_VALOR_CADENA4 = 'S 400'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'ACC-CER-001TG';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA1 = 'CERRADURA ELECTROMAGNETICA', VC_VALOR_CADENA3='SECO LARM',VC_VALOR_CADENA4 = 'E-942FC-1300'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'CER-ELEC-0001';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA1 = 'CÁMARA PTZ OUTDOOR'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'CMR-OUT-0001';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA3='ZKTEKO',VC_VALOR_CADENA4 = 'KR500-E'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'LEC-RFID-0001';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA3='AIO SYSTEMS',VC_VALOR_CADENA4 = '-'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'KIT-LIGHT-0001';
UPDATE ENTIDAD_DET
SET VC_VALOR_CADENA3='STARLUX',VC_VALOR_CADENA4 = 'ST-06B'
WHERE VC_ID_ENTIDAD = 'EQUI' AND VC_ID_VALOR = 'SEN-OCU-0001';


