CREATE TABLE RUTA_CAMPO(
CH_ID_DOCUMENTO CHAR(6),
CH_ID_CAMPO CHAR(6),
VC_VALOR_CADENA1 VARCHAR(2000),
CH_ID_CARPETA CHAR(6),
VC_RUTA_CARPETA VARCHAR(2000)
)

IF OBJECT_ID('USP_ASIGNAR_RUTA_CAMPO') IS NOT NULL
DROP PROC USP_ASIGNAR_RUTA_CAMPO 
GO
CREATE PROC USP_ASIGNAR_RUTA_CAMPO
@CH_ID_CAMPO CHAR(6), @CH_ID_CARPETA CHAR(6)
AS	
	
	DECLARE 
	@VC_VALOR_CADENA VARCHAR(2000),@VC_RUTA_CARPETA VARCHAR(2000),
	@CH_ID_DOCUMENTO CHAR(6);
	BEGIN
	SET @VC_VALOR_CADENA = (SELECT VC_VALOR_CADENA1
							FROM ENTIDAD_DET WHERE
							VC_ID_VALOR = @CH_ID_CAMPO AND
							VC_ID_ENTIDAD = 'CAMP_DOCU');
	SET @VC_RUTA_CARPETA = (SELECT VC_RUTA_CARPETA
							FROM CARPETAS WHERE
							CH_ID_CARPETA = @CH_ID_CARPETA);
	SET @CH_ID_DOCUMENTO = (SELECT CH_ID_DOCUMENTO
							FROM CARPETAS
							WHERE CH_ID_CARPETA = @CH_ID_CARPETA);
	--SET @VC_RUTA_CARPETA1 =	(SELECT VC_RUTA_CARPETA1
							--FROM RUTA_CAMPO);

	--IF (@VC_RUTA_CARPETA1 IS NOT NULL)
		
	--INSERT INTO RUTA_CAMPO(VC_ID_VALOR,VC_VALOR_CADENA1,CH_ID_CARPETA,VC_RUTA_CARPETA2)
	--VALUES(@VC_ID_VALOR,@VC_VALOR_CADENA,@CH_ID_CARPETA,@VC_RUTA_CARPETA)
	--ELSE
		INSERT INTO RUTA_CAMPO(CH_ID_DOCUMENTO,CH_ID_CAMPO,VC_VALOR_CADENA1,CH_ID_CARPETA,VC_RUTA_CARPETA)
		VALUES(@CH_ID_DOCUMENTO,@CH_ID_CAMPO,@VC_VALOR_CADENA,@CH_ID_CARPETA,@VC_RUTA_CARPETA)	
	END
GO
