SELECT T.VC_ID_NODO_IIBB_A,RC.CH_ID_CAMPO,RC.VC_VALOR_CADENA1,
RC.CH_ID_CARPETA,RC.VC_RUTA_CARPETA,DD.VB_VALOR_BINARIO
FROM DOCUMENTO_DET DD 
INNER JOIN RUTA_CAMPO RC ON (DD.CH_ID_CAMPO = RC.CH_ID_CAMPO )
INNER JOIN TAREA T ON (DD.CH_ID_TAREA = T.CH_ID_TAREA)
WHERE T.VC_ID_NODO_IIBB_A LIKE '%AP-0092%' AND RC.CH_ID_DOCUMENTO = DD.CH_ID_DOCUMENTO --AND
--(SUBSTRING(T.VC_ID_NODO_IIBB_A,9,4) ='CS01' OR SUBSTRING(VC_RUTA_CARPETA,2,4)='IE01')

 

SELECT * FROM RUTA_CAMPO
SELECT * FROM DOCUMENTO_DET
SELECT * FROM TAREA
SELECT * FROM CARPETAS

DELETE FROM DOCUMENTO_DET

IF OBJECT_ID('USP_R_RUTA_ZIP') IS NOT NULL
DROP PROC USP_R_RUTA_ZIP
GO
CREATE PROC USP_R_RUTA_ZIP
@VC_ID_NODO VARCHAR(12)
AS
	BEGIN 

	END
GO
