SELECT T.VC_ID_NODO_IIBB_A,C.CH_VALOR_DOCUMENTO,RC.VC_ID_VALOR,RC.VC_VALOR_CADENA1,RC.CH_ID_CARPETA,RC.VC_RUTA_CARPETA1
FROM DOCUMENTO_DET DD 
INNER JOIN RUTA_CAMPO RC ON (DD.CH_ID_CAMPO = RC.VC_ID_VALOR)
INNER JOIN TAREA T ON (DD.CH_ID_TAREA = T.CH_ID_TAREA)
INNER  JOIN CARPETAS C ON (C.CH_VALOR_DOCUMENTO = DD.CH_ID_DOCUMENTO)
WHERE T.VC_ID_NODO_IIBB_A LIKE '%AP-0092%'


SELECT * FROM RUTA_CAMPO
SELECT * FROM CARPETAS
SELECT * FROM DOCUMENTO_DET
SELECT * FROM TAREA