IF OBJECT_ID('USP_R_ZIP_PRUEBA') IS NOT NULL
DROP PROC USP_R_ZIP_PRUEBA
GO
CREATE PROC USP_R_ZIP_PRUEBA
@VC_ID_NODO VARCHAR(12)
AS 
	BEGIN
		SELECT T.VC_ID_NODO_IIBB_A,RC.CH_ID_CAMPO,RC.VC_VALOR_CADENA1,
				RC.CH_ID_CARPETA,RC.VC_RUTA_CARPETA,DD.VB_VALOR_BINARIO, DD.VC_EXTENSION_ARCHIVO
				FROM DOCUMENTO_DET DD 
				INNER JOIN RUTA_CAMPO RC ON (DD.CH_ID_CAMPO = RC.CH_ID_CAMPO )
				INNER JOIN TAREA T ON (DD.CH_ID_TAREA = T.CH_ID_TAREA)
	WHERE T.VC_ID_NODO_IIBB_A LIKE '%'+@VC_ID_NODO+'%' AND RC.CH_ID_DOCUMENTO = DD.CH_ID_DOCUMENTO AND DD.VB_VALOR_BINARIO IS NOT NULL
	AND SUBSTRING(RC.VC_RUTA_CARPETA,2,4)= SUBSTRING(VC_ID_NODO_IIBB_A,9,4) 
	UNION
	
SELECT T.VC_ID_NODO_IIBB_A,RC.CH_ID_CAMPO,RC.VC_VALOR_CADENA1,
				RC.CH_ID_CARPETA,RC.VC_RUTA_CARPETA,DD.VB_VALOR_BINARIO, DD.VC_EXTENSION_ARCHIVO
				FROM DOCUMENTO_DET DD 
				INNER JOIN RUTA_CAMPO RC ON (DD.CH_ID_CAMPO = RC.CH_ID_CAMPO )
				INNER JOIN TAREA T ON (DD.CH_ID_TAREA = T.CH_ID_TAREA)
		WHERE T.VC_ID_NODO_IIBB_A=@VC_ID_NODO AND RC.CH_ID_DOCUMENTO = DD.CH_ID_DOCUMENTO AND DD.VB_VALOR_BINARIO IS NOT NULL
	END
GO



