

IF OBJECT_ID( 'USP_R_EXCEL_IN_ZIP') IS NOT NULL 
DROP PROC USP_R_EXCEL_IN_ZIP
GO
CREATE PROC USP_R_EXCEL_IN_ZIP
@VC_ID_NODO VARCHAR(12)
AS
	BEGIN		
		SELECT  DISTINCT (DD.CH_ID_DOCUMENTO), T.CH_ID_TAREA, ED.VC_VALOR_CADENA1,T.CH_ID_TIP_NODO_A
		FROM DOCUMENTO_DET DD INNER JOIN ENTIDAD_DET ED ON
		(DD.CH_ID_DOCUMENTO = ED.VC_ID_VALOR AND VC_ID_ENTIDAD = 'DOCU')
		INNER JOIN TAREA T ON T.CH_ID_TAREA  = DD.CH_ID_TAREA
		WHERE T.VC_ID_NODO_IIBB_A LIKE '%'+@VC_ID_NODO+'%'
		ORDER BY T.CH_ID_TAREA ASC
	END
GO	

