IF OBJECT_ID('USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_IIBB_B') IS NOT NULL
DROP PROC USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_IIBB_B
GO
CREATE PROC USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_IIBB_B
@CH_ID_TAREA CHAR(7)
AS 
	DECLARE @IMAGEN varbinary(MAX);
	SET @IMAGEN = (SELECT VB_VALOR_BINARIO1
				FROM ENTIDAD_DET
				WHERE VC_ID_ENTIDAD = 'CAMP_VACIO' 
				AND VC_ID_VALOR = '000001');

	BEGIN	
	--CARATULA
		SELECT(SELECT VC_VALOR_CAMPO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000001') AS FRECUENCIA, 

		(SELECT IB.CH_ID_IIBB
		FROM TAREA T INNER JOIN INSTITUCION_BENEFICIARIA IB
		ON T.VC_ID_NODO_IIBB_A = IB.CH_ID_IIBB
		WHERE T.CH_ID_TAREA =@CH_ID_TAREA ) AS CODIGO_IIBB,

		(SELECT T.CH_ID_NODO_B
		FROM TAREA T
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS CODIGO_NODO,

		(SELECT IPP.VC_IP_IIBB
		FROM IP_PLANNING_PMP_DET IPP INNER JOIN TAREA T
		ON IPP.CH_ID_IIBB = T.VC_ID_NODO_IIBB_A
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS IP_IIBB,

		( SELECT TIP_IIBB.VC_VALOR_CADENA1 
		FROM TAREA T LEFT JOIN	ENTIDAD_DET TIP_IIBB ON (TIP_IIBB.VC_ID_ENTIDAD = 'TIP_IIBB'
		AND SUBSTRING(T.VC_ID_NODO_IIBB_A,9,2) = TIP_IIBB.VC_ID_VALOR)
		WHERE LEN(VC_ID_NODO_IIBB_A) > 7 AND CH_ID_TAREA = @CH_ID_TAREA ) AS TIPO_INSTITUCION,

		(SELECT IB.VC_NOMBRE
		FROM TAREA T INNER JOIN INSTITUCION_BENEFICIARIA IB
		ON T.VC_ID_NODO_IIBB_A = IB.CH_ID_IIBB
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA	) AS NOMBRE_IIBB,

		(SELECT DT_VALOR_FECHA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000002') AS FECHA,
-----------------------------------------------------------------------
	--ACTA INSTALACION FITEL
		(SELECT  D.VC_NOMBRE
		FROM TAREA T INNER JOIN NODO N
		ON T.CH_ID_NODO_B = N.CH_ID_NODO
		INNER JOIN DEPARTAMENTO D ON (D.CH_ID_DEPARTAMENTO = N.CH_ID_DEPARTAMENTO)
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS DEPARTAMENTO,

		(SELECT P.VC_NOMBRE
		FROM TAREA T INNER JOIN NODO N 
		ON T.CH_ID_NODO_B = N.CH_ID_NODO
		INNER JOIN PROVINCIA P ON (P.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA)
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND
		P.CH_ID_DEPARTAMENTO = N.CH_ID_DEPARTAMENTO ) AS PROVINCIA,

		(SELECT D.VC_NOMBRE
		FROM TAREA T INNER JOIN NODO N
		ON T.CH_ID_NODO_B = N.CH_ID_NODO 
		INNER JOIN DISTRITO D ON (D.CH_ID_DISTRITO = N.CH_ID_DISTRITO)
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND 
		D.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA
		AND D.CH_ID_DEPARTAMENTO =N.CH_ID_DEPARTAMENTO) AS DISTRITO,

		(SELECT IB.VC_NOMBRE
		FROM TAREA T INNER JOIN INSTITUCION_BENEFICIARIA IB
		ON T.VC_ID_NODO_IIBB_A = IB.CH_ID_IIBB
		WHERE T.CH_ID_TAREA=@CH_ID_TAREA) AS NOMBRE_NODO,

		(SELECT N.CH_ID_UBIGEO
		FROM TAREA T INNER JOIN NODO N 
		ON T.CH_ID_NODO_B = N.CH_ID_NODO
		WHERE  T.CH_ID_TAREA = @CH_ID_TAREA) AS UBIGEO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000004') AS LATITUD,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000005') AS LONGITUD,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000006') AS ALTITUDmsnm,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000007') AS AZIMUT,
----------------------------------------------------------------------------
		
		--

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000075') AS DIRECCION_NODO,

		--EQUIPAMIENTOS
		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'ICA0066') AS ODU_CPE,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'NWCIRRXR-620') AS ACCESS_POINT_INDOOR,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'NWDLDGS121010P') AS SWITCH_COMUNICACIONES,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'NWMKRB750GR3') AS ROUTER,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=1) AS EQUIPO_COMPUTO1,

		
		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=2) AS EQUIPO_COMPUTO2,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=3) AS EQUIPO_COMPUTO3,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=4) AS EQUIPO_COMPUTO4,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=5) AS EQUIPO_COMPUTO5,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PRHPOJ8710') AS IMPRESORA_MULTIFUNCIONAL,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'UPSLIGTX-MT-KIT') AS UPS,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000280') AS REFERENCIA_UBICACION_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000281') AS TIPO_MASTIL,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000282') AS ALTURA_MASTIL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000283') AS DISPONIBILIDAD_HORAS,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000284') AS VALOR_MEDIO_MEDIDA1,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000285') AS VALOR_MEDIO_MEDIDA2,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000286') AS VALOR_MEDIO_MEDIDA3,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000287') AS POTENCIA_TRANSMISION,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000288') AS ANCHO_BANDA_CANAL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000289') AS ELEVACION,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000290') AS CONECTIVIDAD_GILAT,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000291') AS CONECTIVIDAD_NODO_TERMINAL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000292') AS CONECTIVIDAD_NODO_DISTRITAL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000293') AS CONECTIVIDAD_NOC,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000294') AS NOMBRES_APELLIDOS_ENCARGADO,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000295') AS DOC_IDENTIDAD_ENCARGADO,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000296') AS CELULAR_CONTACTO_ENCARGADO,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000297') AS EMAIL_ENCARGADO_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000298') AS NOMBRES_APELLIDOS_REPRESENTANTE,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000299') AS DOC_IDENTIDAD_REPRESENTANTE,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000300') AS CELULAR_CONTACTO_REPRESENTANTE,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000301') AS CARGO_REPRESENTANTE_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000302') AS EMAIL_REPRESENTANTE_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000303') AS NOMBRES_APELLIDOS_REPR_OPERADOR,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000304') AS DOC_IDENTIDAD_REPR_OPERADOR,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000305') AS CARGO_REPRESENTANTE_OPERADOR,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000306') AS EMAIL_REPR_OPERADOR,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000307') AS PANT_CONF_ACCESS_POINt,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000308') AS PANT_CONF_ROUTER,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000309') AS PANT_CONF_SWITCH01,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000310') AS PANT_CONF_SWITCH02,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000311') AS PANT_CONF_UPS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000312') AS PANT_CONF_ALLINONE01,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000313') AS PANT_CONF_ALLINONE02,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000314') AS PANT_CONF_IMPRESORA,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000315') AS MSPT_MEDIDA1_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000316') AS MSPT_MEDIDA2_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000317') AS MSPT_MEDIDA3_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000318') AS MSPTP_MEDIDA1_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000319') AS MSPTP_MEDIDA2_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000320') AS MSPTP_MEDIDA3_VALORMEDIO,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000321') AS FOTO1_PAN_LOCALIDAD,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000322') AS FOTO2_FACHADA_INSTITUCION,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000323') AS FOTO3_1_IMPRESORA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000324') AS FOTO3_2_SWITCH,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000325') AS FOTO3_3_ROUTER,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000326') AS FOTO3_4_PC_ENCENDIDAS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000327') AS FOTO3_5_PC_UPS,
			
		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000328') AS FOTO3_6_ACCESS_POINT,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000329') AS FOTO4_1_ODU_CPE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000330') AS FOTO4_2_MASTIL,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000331') AS FOTO4_3_PAN_ANT_INSTAL_MASTIL,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000332') AS FOTO4_4_RECORRIDO_SFTP_CATSE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000333') AS FOTO4_5_INGRESO_SFTP,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000334') AS FOTO4_6_RECORRIDO_SFTP_CANALETA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000335') AS FOTO4_7_POE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000336') AS FOTO4_8_PATCH_POE_ROUTER,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000337') AS FOTO5_1_TABLERO_GENERAL_SECUNDARIO,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000338') AS FOTO5_2_INSTALACION_BREAKER,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000339') AS FOTO5_3_CABLE_CONEXION_ELECTRICA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000340') AS FOTO5_4_TOMAS_ENERGIA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000341') AS FOTO5_5_FOTO_INTERNA_INST_BREAKER,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000342') AS FOTO6_1_DNI_DJREPRESENTANTE_ABONADO,

			(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000343') AS FOTO6_2_DNI_DJREPRESENTANTE_ABONADO,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000344') AS FOTO7_1_SWITCH,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000345') AS FOTO7_2_ROUTER,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000346') AS FOTO7_3_REGLETA_ENERGIA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000347') AS FOTO7_4_UPS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000348') AS FOTO7_5_COMPUTADORAS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000349') AS FOTO7_6_ACESS_POINT,

			(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000350') AS FOTO7_7_IMPRESORA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000351') AS FOTO7_8_PAN_SALA_EQUIPOS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000352') AS FOTO7_9_JACK_RJ45,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000353') AS FOTO8_1_INSTALACION_POZO_TIERRA,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000354') AS FOTO8_2_CONEX_CAJA_REGISTRO,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000355') AS FOTO8_3_ESCALA_UTIL_RESULT_MEDICION1,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000356') AS FOTO8_4_ESCALA_UTIL_RESULT_MEDICION2,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000357') AS FOTO8_5_ESCALA_UTIL_RESULT_MEDICION3,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000358') AS FOTO9_1_INSTAL_POZO_TIERRA_1,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000359') AS FOTO9_2_INSTAL_POZO_TIERRA_2,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000360') AS FOTO9_3_ESCALA_UTIL_RESULT_MEDICION1,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000361') AS FOTO9_4_ESCALA_UTIL_RESULT_MEDICION2,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000362') AS FOTO9_5_ESCALA_UTIL_RESULT_MEDICION3,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000363') AS FOTO10_1_PANT_CONF_HOME,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000364') AS FOTO10_2_PANT_CONF_SECURITY,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000365') AS FOTO10_3_PANT_CONF_RADIO_1,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000366') AS FOTO10_4_PANT_CONF_RADIO_2,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000367') AS FOTO10_5_CONF_SISTEMA_1,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000368') AS FOTO10_6_CONF_SISTEMA_2,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000369') AS FOTO10_7_PANT_CONF_NETWORK_1,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000370') AS FOTO10_8_PANT_CONF_NETWORK_2,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000371') AS FOTO10_9_PANT_CONF_MONITOR_WIRELESS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000372') AS FOTO10_10_CONF_SISTEMA_TOOLS,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000373') AS FOTO11_1_MON_CONEX_SITIO_WEB,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000374') AS FOTO11_2_MON_CONECTIVIDAD_NODO_TERMINAL,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000375') AS FOTO11_3_MON_CONECTIVIDAD_NODO_DISTRITAL,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000376') AS FOTO_EPMP_1000_FORCE_180,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000377') AS FOTO_1_ACCESS_POINT_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000378') AS FOTO_2_SWITCH_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000379') AS FOTO_3_ROUTER_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000380') AS FOTO_4_IMPRESORA_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000381') AS FOTO_5_UPS_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000382') AS FOTO_6_PC01_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000383') AS FOTO_7_PC02_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000384') AS FOTO_8_PC03_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000385') AS FOTO_9_PC04_SERIE,

		(SELECT ISNULL(VB_VALOR_BINARIO,@IMAGEN)
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000386') AS FOTO_10_PC05_SERIE
END
		