IF OBJECT_ID('USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_IIBB') IS NOT NULL
DROP PROC USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_IIBB
GO
CREATE PROC USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_IIBB
@CH_ID_TAREA CHAR(7)
AS 
	BEGIN	
		SELECT(SELECT VC_VALOR_CAMPO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000001') AS FRECUENCIA, 

		(SELECT DT_VALOR_FECHA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000002') AS FECHA,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000004') AS LATITUD,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000005') AS LONGITUD,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000006') AS ALTITUDmsnm,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000007') AS AZIMUT,


		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'ICD001548') AS POWER_CABLE_3X14AWG_FEOR_300V,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'ICD001556') AS RAL_9005_SILICONE_200ML,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'ICD001584') AS ISOLATOR_TEFLON_D40X17,5_L40,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'ICD001589') AS SILICONA_TRANSPARENTE_200ML,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000031') AS STEEL_FLEXIBLE_CONDUIT__DFX,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000033') AS GROUND_CABLE_AWG_6_YELLOW_GREEN,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000037') AS SOPORTE_CPE_TIPO_L,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000038') AS MASTIL_PISO_TECHO_CPE_3M,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000041') AS MASTIL_TIPO_TELESCOPICO_CPE_6M,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000042') AS MASTIL_TIPO_TELESCOPICO_CPE_9M,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000044') AS SOPORTE_CPE_PARARRAYOS_TIPO_BASTON,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'IPE000049') AS MASTIL_ARRIOSTRADO_12M_PARA_CPE,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'M02472') AS DATA_CABLE_CAT5E_FOR_OUTDOOR,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'M02475') AS LAN_CABLE_CAT5E_UTP_24AWG_LSZH_GREY,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'M10189') AS CABLE_ARG7R_0,6/1KV_50MMQ_ALUMINUM_BLACK,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'MASTIL') AS MASTIL_GENERICO,

		(SELECT IN_CANTIDAD
		FROM DOCUMENTO_MATERIAL DM 
		WHERE DM.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_MATERIAL = 'N00702') AS PVC_TAPE_25M_X_19MM_BLACK,

		/*(SELECT DT_VALOR_FECHA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000053') AS MEDICIONES_ENLACES_PROPAGACION,*/

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000075') AS DIRECCION_NODO,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'ICA0066') AS ODU_CPE,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'NWCIRRXR-620') AS ACCESS_POINT_INDOOR,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'NWDLDGS121010P') AS SWITCH_COMUNICACIONES,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'NWMKRB750GR3') AS ROUTER,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=1) AS EQUIPO_COMPUTO1,

		
		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=2) AS EQUIPO_COMPUTO2,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=3) AS EQUIPO_COMPUTO3,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=4) AS EQUIPO_COMPUTO4,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PCADAI455601' AND IN_ITEM=5) AS EQUIPO_COMPUTO5,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'PRHPOJ8710') AS IMPRESORA_MULTIFUNCIONAL,

		(SELECT VC_SERIE_EQUIPAMIENTO
		FROM DOCUMENTO_EQUIPAMIENTO DE 
		WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000016' 
		AND VC_ID_EQUIPAMIENTO = 'UPSLIGTX-MT-KIT') AS UPS,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000280') AS REFERENCIA_UBICACION_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000281') AS TIPO_MASTIL,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000282') AS ALTURA_MASTIL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000283') AS DISPONIBILIDAD_HORAS,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000284') AS VALOR_MEDIO_MEDIDA1,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000285') AS VALOR_MEDIO_MEDIDA2,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000286') AS VALOR_MEDIO_MEDIDA3,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000287') AS POTENCIA_TRANSMISION,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000288') AS ANCHO_BANDA_CANAL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000289') AS ELEVACION,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000290') AS CONECTIVIDAD_GILAT,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000291') AS CONECTIVIDAD_NODO_TERMINAL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000292') AS CONECTIVIDAD_NODO_DISTRITAL,

		(SELECT IN_VALOR_ENTERO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000293') AS CONECTIVIDAD_NOC,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000294') AS NOMBRES_APELLIDOS_ENCARGADO,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000295') AS DOC_IDENTIDAD_ENCARGADO,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000296') AS CELULAR_CONTACTO_ENCARGADO,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000297') AS EMAIL_ENCARGADO_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000298') AS NOMBRES_APELLIDOS_REPRESENTANTE,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000299') AS DOC_IDENTIDAD_REPRESENTANTE,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000300') AS CELULAR_CONTACTO_REPRESENTANTE,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000301') AS CARGO_REPRESENTANTE_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000302') AS EMAIL_REPRESENTANTE_IIBB,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000303') AS NOMBRES_APELLIDOS_REPR_OPERADOR,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000304') AS DOC_IDENTIDAD_REPR_OPERADOR,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000305') AS CARGO_REPRESENTANTE_OPERADOR,

		(SELECT VC_VALOR_CADENA
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000306') AS EMAIL_REPR_OPERADOR,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000307') AS PANT_CONF_ACCESS_POIN,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000308') AS PANT_CONF_ROUTER,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000309') AS PANT_CONF_SWITCH01,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000310') AS PANT_CONF_SWITCH02,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000311') AS PANT_CONF_UPS,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000312') AS PANT_CONF_ALLINONE01,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000313') AS PANT_CONF_ALLINONE02,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000314') AS PANT_CONF_IMPRESORA,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000315') AS MSPT_MEDIDA1_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000316') AS MSPT_MEDIDA2_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000317') AS MSPT_MEDIDA3_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000318') AS MSPTP_MEDIDA1_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000319') AS MSPTP_MEDIDA2_VALORMEDIO,

		(SELECT NU_VALOR_NUMERICO
		FROM DOCUMENTO_DET DD
		WHERE DD.CH_ID_TAREA = @CH_ID_TAREA
		AND DD.CH_ID_DOCUMENTO = '000016' 
		AND DD.CH_ID_CAMPO = '000320') AS MSPTP_MEDIDA3_VALORMEDIO,

END
		