IF OBJECT_ID('USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_SECTORIAL') IS NOT NULL
DROP PROC USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_SECTORIAL
GO
CREATE PROC USP_R_ACTA_INSTALACION_ACEPTACION_PROTOCOLO_SECTORIAL
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
				SELECT(SELECT N.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO
				WHERE T.CH_ID_TAREA=@CH_ID_TAREA) AS NOMBRE_NODO,

				(SELECT T.VC_ID_NODO_IIBB_A
				FROM TAREA T INNER JOIN ENTIDAD_DET ED
				ON(T.CH_ID_TIP_NODO_A = ED.VC_ID_VALOR
				AND VC_ID_ENTIDAD = 'TIP_NODO')
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS CODIGO_NODO,

				(SELECT ED.VC_VALOR_CADENA1
				FROM TAREA T INNER JOIN ENTIDAD_DET ED
				ON(T.CH_ID_TIP_NODO_A = ED.VC_ID_VALOR
				AND VC_ID_ENTIDAD = 'TIP_NODO')
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS TIPO_NODO,

				(SELECT DD.VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000001') AS FRECUENCIA,

				(SELECT DD.DT_VALOR_FECHA
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000002') AS FECHA,

				(SELECT  D.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO
				INNER JOIN DEPARTAMENTO D ON (D.CH_ID_DEPARTAMENTO = N.CH_ID_DEPARTAMENTO)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS DEPARTAMENTO,

				(SELECT P.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N 
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO
				INNER JOIN PROVINCIA P ON (P.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND
				P.CH_ID_DEPARTAMENTO = N.CH_ID_DEPARTAMENTO ) AS PROVINCIA,

				(SELECT D.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO 
				INNER JOIN DISTRITO D ON (D.CH_ID_DISTRITO = N.CH_ID_DISTRITO)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND 
				D.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA
				AND D.CH_ID_DEPARTAMENTO =N.CH_ID_DEPARTAMENTO) AS DISTRITO,

				(SELECT DD.VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000003') AS DIRECCION,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000004') AS LATITUD_S,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000005') AS LONGITUD_W,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000006') AS ALTITUD_MSNM,

				(SELECT DD.IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000007') AS AZIMUT,

				(SELECT DD.IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000008') AS DOWN_TILT,

				(SELECT DD.IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000009') AS ALTURA_INST,

				(SELECT IPP.VC_IP_NODO
				FROM IP_PLANNING_PMP_SECTOR IPP INNER JOIN TAREA T 
				ON IPP.CH_ID_NODO = T.VC_ID_NODO_IIBB_A
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS IP_ADDRESS,

				(SELECT IPP.VC_DEF_GATEWAY
				FROM IP_PLANNING_PMP IPP INNER JOIN TAREA T 
				ON IPP.CH_ID_NODO = T.VC_ID_NODO_IIBB_A
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS GATEWAY_IP,

				(SELECT DD.IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000010') AS CAPACIDAD_ENLACE,

				(SELECT DD.IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000011') AS EFICIENCIA_ENLACE,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000012') AS CAP1_CONF_RADIO,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000013') AS CAP2_CONF_QoS,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000014') AS CAP3_1_CONF_SYSTEM,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000015') AS CAP3_2_CONF_SYSTEM,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000016') AS CAP4_MONITOR_SYSTEM,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000017') AS CAP5_1_MON_WIRELESS,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000018') AS CAP5_2_MON_WIRELESS,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000019') AS CAP6_TOOLS_WIRELESS,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000020') AS CAP7_PANTALLA_HOME,

			

			(SELECT  P.IN_ALT_ANT_NODO
			FROM  PMP P INNER JOIN TAREA T 
			ON P.CH_ID_NODO = T.VC_ID_NODO_IIBB_A
			WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS ALTURA_TORRE,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000027') AS DISTANCIA_B,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000028') AS DISTANCIA_C,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000029') AS DISTANCIA_D,

				(SELECT DD.NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000030') AS DISTANCIA_E,

				

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000031') AS FOTO1_PAN_ESTACION_A,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000032') AS FOTO2_P0S_ANTENA_INST,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000033') AS FOTO3_ANTENA_ODU_TORRE,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000034') AS FOTO4_UGPS,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000035') AS FOTO5_ENGRASADO_PERNO,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000036') AS FOTO6_SILICONEADO_ETIQUETADO,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000038') AS FOTO8_RECORRIDO_CABLE_SFTP,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000039') AS FOTO9_ATERRAMIENTO_CABLE_SFTP_OUT,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000040') AS FOTO10_ATERRAMIENTO_CABLE_SFTP_IN,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000041') AS FOTO11_ETIQUETADO_POE,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000042') AS FOTO12_PAN_RACK,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000043') AS FOTO13_ATERRAMIENTO_POE,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000044') AS FOTO14_1_EMERGENCIA_POE_ETIQUETA,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000045') AS FOTO14_2_EMERGENCIA_POE_ETIQUETA,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000046') AS FOTO15_PATCH_CORE_SALIDA_POE,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000047') AS FOTO16_PATCH_CORE_SALIDA_SWITCH,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000048') AS FOTO17_SERIE_POE,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000049') AS FOTO18_SERIE_AP,

				(SELECT DD.VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000050') AS FOTO19_SERIE_ANTENA,

				(SELECT DD.VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000051') AS #SERIE_ODU,

				(SELECT DD.VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD INNER JOIN 
				TAREA T ON  DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_TAREA = @CH_ID_TAREA 
				AND DD.CH_ID_DOCUMENTO = '000001'
				AND DD.CH_ID_CAMPO = '000052') AS #SERIE_ANTENA,

				--CAMPOS SERIALES EQUIPAMIENTOS 

				(SELECT DE.VC_SERIE_EQUIPAMIENTO
				FROM DOCUMENTO_EQUIPAMIENTO  DE INNER JOIN 
				ENTIDAD_DET ED ON (DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR
				 AND ED.VC_ID_ENTIDAD= 'EQUI')
				WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
				AND DE.CH_ID_DOCUMENTO = '000001'
				AND ED.VC_ID_VALOR = 'ICA0064') AS SERIAL_TERMINAL_ACCESS_POINT,

				(SELECT DE.VC_SERIE_EQUIPAMIENTO
				FROM DOCUMENTO_EQUIPAMIENTO  DE INNER JOIN 
				ENTIDAD_DET ED ON (DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR
				 AND ED.VC_ID_ENTIDAD= 'EQUI')
				WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
				AND DE.CH_ID_DOCUMENTO = '000001'
				AND ED.VC_ID_VALOR = 'ICA0093') AS SERIAL_ANTENA_CAMBIUM_5GHZ,

				(SELECT DE.VC_SERIE_EQUIPAMIENTO
				FROM DOCUMENTO_EQUIPAMIENTO  DE INNER JOIN 
				ENTIDAD_DET ED ON (DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR
				 AND ED.VC_ID_ENTIDAD= 'EQUI')
				WHERE DE.CH_ID_TAREA = @CH_ID_TAREA
				AND DE.CH_ID_DOCUMENTO = '000001'
				AND ED.VC_ID_VALOR = 'ICD001578') AS SERIAL_POE_INYECTOR,
			
				(SELECT N.CH_ID_UBIGEO
				FROM TAREA T INNER JOIN NODO N 
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO
				WHERE  T.CH_ID_TAREA = @CH_ID_TAREA) AS UBIGEO,

				(SELECT VC_ID_SECTOR_AP
				FROM TAREA
				WHERE CH_ID_TAREA = @CH_ID_TAREA) AS SITE_NAME_SSID,

				(SELECT LEFT(VC_PUERTO_NODO,9)
				FROM IP_PLANNING_PMP_SECTOR IPP
				 INNER JOIN TAREA T 
				ON IPP.CH_ID_NODO  = T.VC_ID_NODO_IIBB_A
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS MODELO_PUERTO_NODO, 

				(SELECT RIGHT(VC_PUERTO_NODO,2)
				FROM IP_PLANNING_PMP_SECTOR IPP
				 INNER JOIN TAREA T 
				ON IPP.CH_ID_NODO  = T.VC_ID_NODO_IIBB_A
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS PUERTO_NODO
	END


