IF OBJECT_ID('ACTA_INSTALACION_PTP_LIC') IS NOT NULL
DROP PROC ACTA_INSTALACION_PTP_LIC
GO
CREATE PROC ACTA_INSTALACION_PTP_LIC
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
		SELECT(SELECT DT_VALOR_FECHA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000002')AS FECHA,

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000084')AS DIREC_ESTACION_A,

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000085')AS DIREC_ESTACION_B,

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000086')AS REF_UBIC_EST_A,

				(SELECT DT_VALOR_FECHA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000087')AS REF_UBIC_EST_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000088')AS NIVEL_RECEP_RADIO_A,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000089')AS NIVEL_RECEP_RADIO_B,

				(SELECT IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000090')AS PING_PTP_RADIO_A,

				(SELECT IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000091')AS PING_PTP_RADIO_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000092')AS CONF_GEN_ENL_EST_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000093')AS CONF_GEN_ENL_EST_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000094')AS CONF_VLAN_ESTA_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000095')AS CONF_VLAN_ESTA_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000096')AS CONF_RADIO_ESTAC_A_1,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000097')AS CONF_RADIO_ESTAC_A_2,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000098')AS CONF_RADIO_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000099')AS CONF_IP_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000100')AS CONF_IP_ESTAC_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000105')AS DIRECCION_B_ESTAC_A,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000106')AS DIRECCION_C_ESTAC_A,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000107')AS DIRECCION_D_ESTAC_A,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000108')AS DIRECCION_E_ESTAC_A,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000109')AS DIRECCION_B_ESTAC_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000110')AS DIRECCION_C_ESTAC_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000111')AS DIRECCION_D_ESTAC_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000112')AS DIRECCION_E_ESTAC_B,

				(SELECT IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000113')AS CAP_BREAKER_ASIG_EST_A,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000114')AS VOLT_DC_ESTAC_A,

				(SELECT IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000115')AS POS_BREAKER_ASIG_ESTAC_A,

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000116')AS POS_BARRA_ATERRA_ESTA_A,

				(SELECT IN_VALOR_ENTERO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000117')AS CAP_BREAKER_ASIG_EST_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000118')AS VOLT_DC_ESTAC_B,

				(SELECT NU_VALOR_NUMERICO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000119')AS POS_BREAKER_ASIG_ESTAC_B,

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000120')AS POS_BARRA_ATERRA_ESTA_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000121')AS INGENIERIA,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000122')AS PERFIL,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000123')AS PANT_RADIO_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000124')AS PANT_RADIO_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000125')AS SERIE_ANT_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000126')AS SERIE_ODU_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000127')AS SERIE_POE_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000131')AS SERIE_ANT_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000132')AS SERIE_ODU_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000133')AS SERIE_POE_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000137')AS FOTO1_PAN_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000138')AS FOTO2_POS_ANT_INST_TORRE_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000139')AS FOTO3_FOTO_ANTENA_PTP_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000140')AS FOTO4_ETIQ_PUERTO_ANT_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000141')AS FOTO5_ENGRAS_PERNOS_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000142')AS FOTO6_SILC_CONECT_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000143')AS FOTO7_ATERRAM_ODU_TORRE_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000144')AS FOTO8_RECORRI_SFTP_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000145')AS FOTO9_1__SFTP_OUT_1_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000146')AS FOTO9_2_SFTP_OUT_2_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000147')AS FOTO10_SALAN_OUT_ETIQ_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000148')AS FOTO11_ATERRAM_SALAN_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000151')AS FOTO14_1_SFTP_IN_1_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000152')AS FOTO14_2_SFTP_IN_2_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000156')AS FOTO17_FOTO_PAN_RACK_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000157')AS FOTO18_1_ATERRAM_POE_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000158')AS FOTO18_2_ATERRAM_POE_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000159')AS FOTO19_1_ENERG_POE_ETIQ_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000160')AS FOTO19_2_ENERG_POE_ETIQ_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000161')AS FOTO20_1_PATCH_POE_ESTAC_A,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000162')AS FOTO20_2_PATCH_POE_ESTAC_A,

				--ESTACION B 
				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000163')AS FOTO1_PAN_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000164')AS FOTO2_POS_ANT_INST_TORRE_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000165')AS FOTO3_FOTO_ANTENA_PTP_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000166')AS FOTO4_ETIQ_PUERTO_ANT_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000167')AS FOTO5_ENGRAS_PERNOS_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000168')AS FOTO6_SILC_CONECT_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000169')AS FOTO7_ATERRAM_ODU_TORRE_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000170')AS FOTO8_RECORRI_SFTP_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000171')AS FOTO9_1__SFTP_OUT_1_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000172')AS FOTO9_2_SFTP_OUT_2_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000173')AS FOTO10_SALAN_OUT_ETIQ_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000174')AS FOTO11_ATERRAM_SALAN_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000177')AS FOTO14_1_SFTP_IN_1_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000178')AS FOTO14_2_SFTP_IN_2_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000182')AS FOTO17_FOTO_PAN_RACK_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000183')AS FOTO18_1_ATERRAM_POE_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000184')AS FOTO18_2_ATERRAM_POE_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000185')AS FOTO19_1_ENERG_POE_ETIQ_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000186')AS FOTO19_2_ENERG_POE_ETIQ_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000187')AS FOTO20_1_PATCH_POE_ESTAC_B,

				(SELECT VB_VALOR_BINARIO
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000188')AS FOTO20_2_PATCH_POE_ESTAC_B,
-------------------------------------------------------------------------------

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000189')AS SERIE_PTP_450__A,

				(SELECT VC_VALOR_CADENA
				FROM DOCUMENTO_DET DD
				WHERE CH_ID_DOCUMENTO='000008' AND
				CH_ID_TAREA = @CH_ID_TAREA AND
				CH_ID_CAMPO = '000191')AS SERIE_PTP_450_B,

	--VALORES FUERA DEL FORMULARIO 

				(SELECT CH_ID_NODO_A
				FROM PTP_DET
				WHERE CH_ID_TAREA= @CH_ID_TAREA) AS NODO_A,

				(SELECT CH_ID_NODO_B
				FROM PTP_DET
				WHERE CH_ID_TAREA= @CH_ID_TAREA) AS NODO_B,

				(SELECT ED.VC_VALOR_CADENA1
				FROM TAREA T INNER JOIN ENTIDAD_DET ED
				ON(T.CH_ID_TIP_NODO_A = ED.VC_ID_VALOR
				AND VC_ID_ENTIDAD = 'TIP_NODO')
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS TIPO_NODO_A,

				(SELECT ED.VC_VALOR_CADENA1
				FROM TAREA T INNER JOIN ENTIDAD_DET ED
				ON(T.CH_ID_TIP_NODO_B = ED.VC_ID_VALOR
				AND VC_ID_ENTIDAD = 'TIP_NODO')
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS TIPO_NODO_B,

				(SELECT N.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO
				WHERE T.CH_ID_TAREA= @CH_ID_TAREA ) AS NOMBRE_NODO_A,

				(SELECT N.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.CH_ID_NODO_B = N.CH_ID_NODO
				WHERE T.CH_ID_TAREA= @CH_ID_TAREA) AS NOMBRE_NODO_B,

				(SELECT SUBSTRING(VC_MOD_RAD_NODO_A,5,2)
				FROM PTP_DET	
				WHERE CH_ID_TAREA = @CH_ID_TAREA) AS FRECUENCIA,

				(SELECT D.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO 
				INNER JOIN DISTRITO D 
				ON (D.CH_ID_DISTRITO = N.CH_ID_DISTRITO)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND 
				D.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA
				AND D.CH_ID_DEPARTAMENTO =N.CH_ID_DEPARTAMENTO) AS DISTRITO_A,

				(SELECT D.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N
				ON T.CH_ID_NODO_B = N.CH_ID_NODO 
				INNER JOIN DISTRITO D 
				ON (D.CH_ID_DISTRITO = N.CH_ID_DISTRITO)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND 
				D.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA
				AND D.CH_ID_DEPARTAMENTO =N.CH_ID_DEPARTAMENTO) AS DISTRITO_B,

				(SELECT P.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N 
				ON T.VC_ID_NODO_IIBB_A = N.CH_ID_NODO
				INNER JOIN PROVINCIA P ON
				 (P.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND
				P.CH_ID_DEPARTAMENTO = N.CH_ID_DEPARTAMENTO) AS PROVINCIA_A,

				(SELECT P.VC_NOMBRE
				FROM TAREA T INNER JOIN NODO N 
				ON T.CH_ID_NODO_B = N.CH_ID_NODO
				INNER JOIN PROVINCIA P ON 
				(P.CH_ID_PROVINCIA = N.CH_ID_PROVINCIA)
				WHERE T.CH_ID_TAREA = @CH_ID_TAREA AND
			P.CH_ID_DEPARTAMENTO = N.CH_ID_DEPARTAMENTO	) AS PROVINCIA_B

	END
GO

