iF OBJECT_ID ('USP_R_ANEXO_02_INVENTARIO_PTP') IS NOT NULL
DROP PROC USP_R_ANEXO_02_INVENTARIO_PTP 
GO
CREATE PROC USP_R_ANEXO_02_INVENTARIO_PTP
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
		--ESTACION A 

		SELECT(SELECT  P.CH_ID_NODO_A
		FROM TAREA T INNER JOIN PTP_DET P
		ON T.CH_ID_TAREA = P.CH_ID_TAREA
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS COD_NODO_A,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000012' 
		AND CH_ID_CAMPO = '000125') AS SERIE_ANTENA_EST_A,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000012' 
		AND CH_ID_CAMPO = '000126') AS SERIE_ODU_EST_A,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000012' 
		AND CH_ID_CAMPO = '000127') AS SERIE_POE_EST_A,

		--ESTACION B

		(SELECT  P.CH_ID_NODO_B
		FROM TAREA T INNER JOIN PTP_DET P
		ON T.CH_ID_TAREA = P.CH_ID_TAREA
		WHERE T.CH_ID_TAREA = @CH_ID_TAREA) AS COD_NODO_B,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000012' 
		AND CH_ID_CAMPO = '000131') AS SERIE_ANTENA_EST_B,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000012' 
		AND CH_ID_CAMPO = '000132') AS SERIE_ODU_EST_B,

		(SELECT VB_VALOR_BINARIO
		FROM DOCUMENTO_DET DD
		WHERE CH_ID_TAREA = @CH_ID_TAREA
		AND CH_ID_DOCUMENTO = '000012' 
		AND CH_ID_CAMPO = '000133') AS SERIE_POE_EST_B

	END
GO