IF OBJECT_ID('USP_R_REPORTE_CMM4') IS NOT NULL
DROP PROC USP_R_REPORTE_CMM4
GO
CREATE PROC USP_R_REPORTE_CMM4
@CH_ID_TAREA CHAR(7)
AS
	BEGIN 
		SELECT(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000059') AS FOTO_1_EQUIPO_GPS,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000060') AS FOTO2_1_ATERRAMIENTO_GPS,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000061') AS FOTO2_2_ATERRAMIENTO_GPS,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000062') AS FOTO3_RECORRIDO_CABLE_CNT300,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000063') AS FOTO4_1_ATERRAMIENTO_CABLE_CNT300,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000064') AS FOTO4_2_ATERRAMIENTO_CABLE_CNT300,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000065') AS FOTO5_1_ETIQUETADO_POE_CMM4,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000066') AS FOTO5_2_ETIQUETADO_POE_CMM4,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000067') AS FOTO6_1_PATCH_CORE,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000068') AS FOTO6_2_PATCH_CORE,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000069') AS FOTO7_1_POE_CMM4,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000070') AS FOTO7_2_POE_CMM4,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000071') AS FOTO8_TDK_LAMBDA,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000072') AS FOTO9_1_ENERGIA_TDK_LAMBDA,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000073') AS FOTO9_2_ENERGIA_TDK_LAMBDA,

		(SELECT VB_VALOR_BINARIO
		FROM  DOCUMENTO_DET DD 
		WHERE DD.CH_ID_TAREA=@CH_ID_TAREA  AND
		 DD.CH_ID_DOCUMENTO = '000006'
		AND DD.CH_ID_CAMPO = '000074') AS FOTO10_CONEXION_TDK_CMM4
		
	END
GO
