
IF OBJECT_ID('USP_ASIGNAR_RUTA_CAMPO') IS NOT NULL
DROP PROC USP_ASIGNAR_RUTA_CAMPO 
GO
CREATE PROC USP_ASIGNAR_RUTA_CAMPO
@VC_ID_VALOR VARCHAR(20), @CH_ID_CARPETA CHAR(7)
AS	
	BEGIN
	DECLARE 
	@VC_VALOR_CADENA VARCHAR(2000),@VC_RUTA_CARPETA VARCHAR(2000);
	--@VC_RUTA_CARPETA1 VARCHAR(2000);
	SET @VC_VALOR_CADENA = (SELECT VC_VALOR_CADENA1
							FROM ENTIDAD_DET WHERE
							VC_ID_VALOR = @VC_ID_VALOR AND
							VC_ID_ENTIDAD = 'CAMP_DOCU');
	SET @VC_RUTA_CARPETA = (SELECT VC_RUTA_CARPETA
							FROM CARPETAS WHERE
							CH_ID_CARPETA = @CH_ID_CARPETA);
	--SET @VC_RUTA_CARPETA1 =	(SELECT VC_RUTA_CARPETA1
							--FROM RUTA_CAMPO);

	--IF (@VC_RUTA_CARPETA1 IS NOT NULL)
		
	--INSERT INTO RUTA_CAMPO(VC_ID_VALOR,VC_VALOR_CADENA1,CH_ID_CARPETA,VC_RUTA_CARPETA2)
	--VALUES(@VC_ID_VALOR,@VC_VALOR_CADENA,@CH_ID_CARPETA,@VC_RUTA_CARPETA)
	--ELSE
		INSERT INTO RUTA_CAMPO(VC_ID_VALOR,VC_VALOR_CADENA1,CH_ID_CARPETA,VC_RUTA_CARPETA1)
		VALUES(@VC_ID_VALOR,@VC_VALOR_CADENA,@CH_ID_CARPETA,@VC_RUTA_CARPETA)	
	END
GO
