USE [SIAEDES]
GO

/****** Object:  StoredProcedure [dbo].[USP_R_EQUIPAMIENTOS_SEGURIDAD_DISTRIBUCION]    Script Date: 25/04/2018 10:41:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_R_EQUIPAMIENTOS_SEGURIDAD_DISTRIBUCION]
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
		SELECT ED.VC_VALOR_CADENA1 EQUIPO,ED.VC_VALOR_CADENA3 MARCA,
				ED.VC_VALOR_CADENA4 MODELO,DE.VC_SERIE_EQUIPAMIENTO Nro_SERIE
		FROM DOCUMENTO_EQUIPAMIENTO DE INNER JOIN ENTIDAD_DET ED
		ON DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR AND ED.VC_ID_ENTIDAD = 'EQUI'
		WHERE DE.CH_ID_TAREA= @CH_ID_TAREA AND DE.CH_ID_DOCUMENTO = '000014'
	END
GO


