IF OBJECT_ID ('USP_R_EQUIPAMIENTOS_SEGURIDAD_ACCESO') IS NOT NULL
DROP PROC USP_R_EQUIPAMIENTOS_SEGURIDAD_ACCESO
GO
CREATE PROC USP_R_EQUIPAMIENTOS_SEGURIDAD_ACCESO
@CH_ID_TAREA CHAR(7)
AS
--TIPO NODO: DISTRIBUCION = 000004, DISTRITAL=000005,INTERMEDIO=000006
		-- INTERMEDIO-AISLADO=000007, TERMINAL=000009
	DECLARE @TIPO_NODO CHAR(6);
	SET @TIPO_NODO= (SELECT CH_ID_TIP_NODO_A
					FROM TAREA WHERE CH_ID_TAREA=@CH_ID_TAREA);
	IF @TIPO_NODO = '000004' --DISTRIBUCION
	BEGIN
		SELECT ED.VC_VALOR_CADENA1 EQUIPO,ED.VC_VALOR_CADENA3 MARCA,
				ED.VC_VALOR_CADENA4 MODELO,DE.VC_SERIE_EQUIPAMIENTO Nro_SERIE
		FROM DOCUMENTO_EQUIPAMIENTO DE INNER JOIN ENTIDAD_DET ED
		ON DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR AND ED.VC_ID_ENTIDAD = 'EQUI'
		WHERE DE.CH_ID_TAREA= @CH_ID_TAREA AND DE.CH_ID_DOCUMENTO = '000013'
		AND (DE.VC_ID_EQUIPAMIENTO = 'CONT-ACC-002' OR DE.VC_ID_EQUIPAMIENTO = 'CONT-ACC-003'
		OR DE.VC_ID_EQUIPAMIENTO = 'SIR-ACC-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-MAG-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-ID-360-001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-OD-090-001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-OCU-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-HUM-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-ANG-0001' OR DE.VC_ID_EQUIPAMIENTO = 'EXT-ACC-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'ACC-CER-001TG' OR DE.VC_ID_EQUIPAMIENTO = 'CER-ELEC-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'LEC-ACC-OD-001' OR DE.VC_ID_EQUIPAMIENTO = 'LEC-ACC-OD-01TG'
		OR DE.VC_ID_EQUIPAMIENTO = 'LEC-RFID-0001' OR DE.VC_ID_EQUIPAMIENTO = 'CMR-OUT-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'CMR-IND-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SIS-GRB-0001' 
		OR DE.VC_ID_EQUIPAMIENTO = 'SIS-GRB-0001TG' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-MAG-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SWT-ACC-0001TG')
	END;
	ELSE IF @TIPO_NODO = '000005' --DISTRITAL
		BEGIN
		SELECT ED.VC_VALOR_CADENA1 EQUIPO,ED.VC_VALOR_CADENA3 MARCA,
				ED.VC_VALOR_CADENA4 MODELO,DE.VC_SERIE_EQUIPAMIENTO Nro_SERIE
		FROM DOCUMENTO_EQUIPAMIENTO DE INNER JOIN ENTIDAD_DET ED
		ON DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR AND ED.VC_ID_ENTIDAD = 'EQUI'
		WHERE DE.CH_ID_TAREA= @CH_ID_TAREA AND DE.CH_ID_DOCUMENTO = '000013'
		AND (DE.VC_ID_EQUIPAMIENTO = 'CONT-ACC-002' OR DE.VC_ID_EQUIPAMIENTO = 'CONT-ACC-003'
		OR DE.VC_ID_EQUIPAMIENTO = 'SIR-ACC-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-MAG-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-ID-360-001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-OD-090-001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-OCU-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-HUM-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-ANG-0001' OR DE.VC_ID_EQUIPAMIENTO = 'EXT-ACC-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'ACC-CER-001TG' OR DE.VC_ID_EQUIPAMIENTO = 'CER-ELEC-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'CMR-OUT-0001' OR DE.VC_ID_EQUIPAMIENTO = 'CMR-IND-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-MAG-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SWT-ACC-0001TG'
		OR DE.VC_ID_EQUIPAMIENTO = 'LEC-RFID-0001' OR DE.VC_ID_EQUIPAMIENTO = 'KIT-LIGHT-0001')
	END;
	ELSE 
		BEGIN
		SELECT ED.VC_VALOR_CADENA1 EQUIPO,ED.VC_VALOR_CADENA3 MARCA,
				ED.VC_VALOR_CADENA4 MODELO,DE.VC_SERIE_EQUIPAMIENTO Nro_SERIE
		FROM DOCUMENTO_EQUIPAMIENTO DE INNER JOIN ENTIDAD_DET ED
		ON DE.VC_ID_EQUIPAMIENTO = ED.VC_ID_VALOR AND ED.VC_ID_ENTIDAD = 'EQUI'
		WHERE DE.CH_ID_TAREA= @CH_ID_TAREA AND DE.CH_ID_DOCUMENTO = '000013'
		AND (DE.VC_ID_EQUIPAMIENTO = 'CONT-ACC-002' OR DE.VC_ID_EQUIPAMIENTO = 'CONT-ACC-003'
		OR DE.VC_ID_EQUIPAMIENTO = 'SIR-ACC-0001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-MAG-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-OD-090-001' OR DE.VC_ID_EQUIPAMIENTO = 'SEN-HUM-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-ANG-0001' OR DE.VC_ID_EQUIPAMIENTO = 'EXT-ACC-0001'	
		OR DE.VC_ID_EQUIPAMIENTO = 'ACC-CER-001TG' OR DE.VC_ID_EQUIPAMIENTO = 'CER-ELEC-0001'
		OR DE.VC_ID_EQUIPAMIENTO = 'CMR-OUT-0001'  OR DE.VC_ID_EQUIPAMIENTO = 'CMR-IND-0002'
		OR DE.VC_ID_EQUIPAMIENTO = 'SEN-MAG-0001'  OR DE.VC_ID_EQUIPAMIENTO = 'SWT-ACC-0001TG'
		OR DE.VC_ID_EQUIPAMIENTO = 'LEC-RFID-0001'  OR DE.VC_ID_EQUIPAMIENTO = 'KIT-LIGHT-0001')
	END;
GO
