USE [SIAEDES]
GO

/****** Object:  StoredProcedure [dbo].[USP_R_MATERIALES_SEGURIDAD_DISTRIBUCION]    Script Date: 25/04/2018 10:41:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('USP_R_MATERIALES_SEGURIDAD_DISTRIBUCION') IS NOT NULL
DROP PROC USP_R_MATERIALES_SEGURIDAD_DISTRIBUCION
GO
CREATE PROC [dbo].[USP_R_MATERIALES_SEGURIDAD_DISTRIBUCION]
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
		SELECT ED.VC_VALOR_CADENA1 DESCRIPCION,ED.VC_ID_VALOR CODIGO,
				ED.VC_VALOR_CADENA2 UNIDAD,DM.NU_CANTIDAD CANTIDAD
		FROM DOCUMENTO_MATERIAL DM INNER JOIN ENTIDAD_DET ED
		ON DM.VC_ID_MATERIAL = ED.VC_ID_VALOR AND ED.VC_ID_ENTIDAD = 'MAT'
		WHERE DM.CH_ID_TAREA= @CH_ID_TAREA AND DM.CH_ID_DOCUMENTO = '000014'
	END
GO


