IF OBJECT_ID('USP_R_MATERIALES_PTP_LIC_B') IS NOT NULL
DROP PROC USP_R_MATERIALES_PTP_LIC_B
GO
CREATE PROC USP_R_MATERIALES_PTP_LIC_B
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
		SELECT ED.VC_VALOR_CADENA1 DESCRIPCION,ED.VC_ID_VALOR CODIGO,
				ED.VC_VALOR_CADENA2 UNIDAD,DM.IN_CANTIDAD CANTIDAD
		FROM DOCUMENTO_MATERIAL DM INNER JOIN ENTIDAD_DET ED
		ON (DM.VC_ID_MATERIAL = ED.VC_ID_VALOR AND ED.VC_ID_ENTIDAD = 'MAT')
		INNER JOIN TAREA T ON (T.CH_ID_TAREA = DM.CH_ID_TAREA AND T.CH_ID_NODO_B=DM.CH_ID_NODO)
		WHERE DM.CH_ID_TAREA= @CH_ID_TAREA AND DM.CH_ID_DOCUMENTO = '000008'
	END
GO