IF OBJECT_ID('USP_R_MEDICION_ENLACE_IIBB_B') IS NOT NULL
DROP  PROC USP_R_MEDICION_ENLACE_IIBB_B
GO
CREATE PROC USP_R_MEDICION_ENLACE_IIBB_B
@CH_ID_TAREA CHAR(7)
AS 
	BEGIN
		
	 SELECT  VC_ID_NODO_IIBB_B CPE,CH_ID_NODO_A ESTACION_LOCAL,NU_RSS_REMOTO	RSS_CPE,NU_RSS_LOCAL RSS_LOCAL,
		NU_TIEMPO_PROMEDIO TIEMPO_PROM, NU_CAPACIDAD_SUBIDA CAP_SUBIDA,NU_CAPACIDAD_BAJADA CAP_BAJADA,
		PD.NU_DISTANCIA*1000 DISTANCIA_metros
	 FROM DOCUMENTO_MED_ENLA_PROP DMP INNER JOIN TAREA T
	    ON  DMP.CH_ID_TAREA = T.CH_ID_TAREA  
		AND DMP.VC_ID_NODO_IIBB_B = T.VC_ID_NODO_IIBB_A
		left JOIN PMP_DET PD ON DMP.VC_ID_NODO_IIBB_B = PD.CH_ID_IIBB
		WHERE t.CH_ID_TAREA = @CH_ID_TAREA
	END
GO

