IF OBJECT_ID('USP_R_MEDICION_SECTORIAL') IS NOT NULL
DROP  PROC USP_R_MEDICION_SECTORIAL
GO
CREATE PROC USP_R_MEDICION_SECTORIAL
@CH_ID_TAREA CHAR(7)
AS 
	BEGIN
		SELECT  CH_ID_NODO_A NODO_A,VC_ID_NODO_IIBB_B IIBB,NU_RSS_LOCAL RSS_LOCAL,NU_RSS_REMOTO	RSS_REMOTO,
		IN_TIEMPO_PROMEDIO TIEMPO_PROM, NU_CAPACIDAD_SUBIDA CAP_SUBIDA,NU_CAPACIDAD_BAJADA CAP_BAJADA,
		PD.NU_DISTANCIA DISTANCIA
		FROM  DOCUMENTO_MED_ENLA_PROP DMP 
		INNER JOIN PMP_DET PD
		ON (DMP.CH_ID_NODO_A = PD.CH_ID_NODO 
		AND DMP.VC_ID_NODO_IIBB_B = PD.CH_ID_IIBB)
		WHERE CH_ID_TAREA = @CH_ID_TAREA
	END
GO

