IF OBJECT_ID('USP_R_ZIP') IS NOT NULL
DROP PROC USP_R_ZIP
GO
CREATE PROC USP_R_ZIP
	@PCH_TIPO_TRANSACCION CHAR(1),
	@PV_ID_NODO_IIBB VARCHAR(12) = NULL,
	@PCH_ID_CONTRATISTA CHAR(6) = NULL,
	@PCH_ID_TAREA CHAR(7) = NULL,
	@PCH_ID_DOCUMENTO CHAR(6) = NULL,
	@PCH_DEVOLVER BIT = 1
AS
	DECLARE @LCH_ID_NODO CHAR(7),
			

