USE [SIAEDES]
GO

/****** Object:  StoredProcedure [dbo].[USP_R_PRUEBAINTERFERENCIA]    Script Date: 13/03/2018 15:11:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[USP_R_PRUEBAINTERFERENCIA]
@CH_ID_TAREA CHAR(7)
AS
	DECLARE @IMAGEN varbinary(MAX);
	SET @IMAGEN = (SELECT VB_VALOR_BINARIO1
				FROM ENTIDAD_DET
				WHERE VC_ID_ENTIDAD = 'CAMP_VACIO' 
				AND VC_ID_VALOR = '000001');
	BEGIN
		SELECT (SELECT T.VC_ID_NODO_IIBB_A
		FROM	TAREA T
		WHERE	CH_ID_TAREA = @CH_ID_TAREA) AS COD_NODO,

		(SELECT	ISNULL(DD.VB_VALOR_BINARIO,@IMAGEN)
		FROM	DOCUMENTO_DET DD
		WHERE	DD.CH_ID_DOCUMENTO = '000003'
		AND		DD.CH_ID_TAREA =@CH_ID_TAREA
		AND		DD.CH_ID_CAMPO = '000054') AS CAP_PANT_EPMP1000
	END
GO

