USE [SIAEDES]
GO

/****** Object:  StoredProcedure [dbo].[USP_R_PRUEBAINTERFERENCIA]    Script Date: 13/03/2018 15:11:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_R_PRUEBAINTERFERENCIA]
@CH_ID_TAREA CHAR(7)
AS
	BEGIN
		SELECT (SELECT	T.VC_ID_NODO_IIBB_A
		FROM	TAREA T
		WHERE	CH_ID_TAREA = @CH_ID_TAREA) AS COD_NODO,
		(SELECT	DD.VB_VALOR_BINARIO
		FROM	DOCUMENTO_DET DD
		WHERE	DD.CH_ID_DOCUMENTO = '000003'
		AND		DD.CH_ID_TAREA =@CH_ID_TAREA
		AND		DD.CH_ID_CAMPO = '000054') AS CAP_PANT_EPMP1000
	END
GO

