iF OBJECT_ID('USP_R_PRUEBAS_SERVICIO_DITG_PTP') IS NOT NULL
DROP PROC USP_R_PRUEBAS_SERVICIO_DITG_PTP
GO
CREATE PROC USP_R_PRUEBAS_SERVICIO_DITG_PTP
@CH_ID_TAREA CHAR(7)
AS
	DECLARE @IMAGEN varbinary(MAX);
	SET @IMAGEN = (SELECT VB_VALOR_BINARIO1
				FROM ENTIDAD_DET
				WHERE VC_ID_ENTIDAD = 'CAMP_VACIO' 
				AND VC_ID_VALOR = '000001');
	BEGIN
		SELECT(SELECT DD.NU_VALOR_NUMERICO 
				 FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				WHERE DD.CH_ID_CAMPO='000193'
				 AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010' ) AS TIEMPO_PRUEBA,

				 (SELECT DD.NU_VALOR_NUMERICO 
				 FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				 WHERE DD.CH_ID_CAMPO='000194'
				 AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010' ) AS RETARDO_MIN,

				 (SELECT DD.NU_VALOR_NUMERICO 
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				 WHERE DD.CH_ID_CAMPO='000195'
				  AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010')  AS RETARDO_MAXIMO,

				 (SELECT DD.NU_VALOR_NUMERICO
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000196'
				  AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS RETARDO_PROMEDIO,

				 (SELECT DD.NU_VALOR_NUMERICO 
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				 WHERE DD.CH_ID_CAMPO='000197'
				  AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS JILTER_PROMEDIO,

				 (SELECT DD.NU_VALOR_NUMERICO 
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				 WHERE DD.CH_ID_CAMPO='000198'
				 AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS DESV_ESTANDAR_RETARDO,

				 (SELECT DD.IN_VALOR_ENTERO 
				 FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				 WHERE DD.CH_ID_CAMPO='000199'
				  AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS BYTES_RECIBIDOS,

				 (SELECT DD.NU_VALOR_NUMERICO
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000200'
				  AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS THROUGHPUT_PROM,

				 (SELECT DD.IN_VALOR_ENTERO 
				 FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				 WHERE DD.CH_ID_CAMPO='000201'
				 AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010' ) AS DESCARTE_PAQUETES,

				 (SELECT ISNULL(DD.VB_VALOR_BINARIO,@IMAGEN)
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000202'
				   AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS PANTALLA_RESULT_PRUEBA_DITG,

				 (SELECT ISNULL(DD.VB_VALOR_BINARIO,@IMAGEN)
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000203'
				   AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS FECHA_HORA_ROUTER,

				 (SELECT ISNULL(DD.VB_VALOR_BINARIO,@IMAGEN)
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000204'
				   AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS PING_TODOS_USUARIOS_MICRO,

				 (SELECT ISNULL(DD.VB_VALOR_BINARIO,@IMAGEN)
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000205'
				   AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS DIRECCIONES_MAC,

				 (SELECT ISNULL(DD.VB_VALOR_BINARIO,@IMAGEN)
				  FROM DOCUMENTO_DET DD INNER JOIN TAREA T 
				 ON DD.CH_ID_TAREA = T.CH_ID_TAREA
				  WHERE DD.CH_ID_CAMPO='000206'
				   AND  DD.CH_ID_TAREA=@CH_ID_TAREA
				AND DD.CH_ID_DOCUMENTO='000010') AS RESULTADO_PRUEBA_DITG

	END
GO


