
CREATE TABLE CARPETAS(
CH_ID_CARPETA CHAR(7) NOT NULL,
VC_RUTA_CARPETA VARCHAR (2000),
CONSTRAINT PK_CH_ID_CARPETA PRIMARY KEY(CH_ID_CARPETA)
);


INSERT INTO CARPETAS VALUES('0000001','\ACCESO\PTP_HC-0XX1 (450i)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\FOTOS\LADO A\CONFIGURACIONES Y MEDICIONES');
INSERT INTO CARPETAS VALUES('0000002','\ACCESO\PTP_HC-0XX1 (450i)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\FOTOS\LADO A\REPORTE FOTOGRÁFICO');
INSERT INTO CARPETAS VALUES('0000003','\ACCESO\PTP_HC-0XX1 (450i)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\FOTOS\LADO B\CONFIGURACIONES Y MEDICIONES');
INSERT INTO CARPETAS VALUES('0000004','\ACCESO\PTP_HC-0XX1 (450i)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\FOTOS\LADO B\REPORTE FOTOGRÁFICO');
INSERT INTO CARPETAS VALUES('0000005','\ACCESO\PTP_HC-0XX2 (alfo)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\LADO A\CONFIGURACIÓN Y MEDICIONES');
INSERT INTO CARPETAS VALUES('0000006','\ACCESO\PTP_HC-0XX2 (alfo)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\LADO A\REPORTE FOTOGRÁFICO');
INSERT INTO CARPETAS VALUES('0000007','\ACCESO\PTP_HC-0XX2 (alfo)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\LADO b\CONFIGURACIÓN Y MEDICIONES');
INSERT INTO CARPETAS VALUES('0000008','\ACCESO\PTP_HC-0XX2 (alfo)\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\LADO A\REPORTE FOTOGRÁFICO');
INSERT INTO CARPETAS VALUES('0000009','\ACCESO\SEGURIDAD DISTRITAL\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\REPORTE FOTOGRÁFICO');
INSERT INTO CARPETAS VALUES('0000010','\ACCESO\SEGURIDAD DISTRITAL\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\VIDEOS');
INSERT INTO CARPETAS VALUES('0000011','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\1. Foto Panorámica de la Estación');
INSERT INTO CARPETAS VALUES('0000012','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\2. Foto de instalación de Antena y ePMP1000');
INSERT INTO CARPETAS VALUES('0000013','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\3. Foto de Engrasado de Pernos');
INSERT INTO CARPETAS VALUES('0000014','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\4. Foto de Rotulado de la Antena');
INSERT INTO CARPETAS VALUES('0000015','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\5. Fotos de recorrido de Cable SFTP Cat5e');
INSERT INTO CARPETAS VALUES('0000016','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\6. Fotos de Aterramiento Cable STFP Cat5e' );
INSERT INTO CARPETAS VALUES('0000017','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\7. Fotos del PoE');
INSERT INTO CARPETAS VALUES('0000018','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\8. Foto de Rack');
INSERT INTO CARPETAS VALUES('0000019','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\9. Foto de energía de PoE');
INSERT INTO CARPETAS VALUES('0000020','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\10. Fotos de Switch');
INSERT INTO CARPETAS VALUES('0000021','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\11. Fotos de Series de Equipos');
INSERT INTO CARPETAS VALUES('0000022','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\12. Foto de Aterramiento de SA-LAN outdoor');
INSERT INTO CARPETAS VALUES('0000023','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\13. Fotos de SA-LAN outdoor');
INSERT INTO CARPETAS VALUES('0000024','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\14. Pantallas Capturadas')
INSERT INTO CARPETAS VALUES('0000025','\ACCESO\PMP\CARPETA DE FOTOS CAPTURAS DE PANTALLA\Foto de Aterramiento de Antena');
INSERT INTO CARPETAS VALUES('0000026','\TRANSPORTE\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\REEPORTE FOTOGRÁFICO');	
INSERT INTO CARPETAS VALUES('0000027','\TRANSPORTE\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\VIDEOS');
INSERT INTO CARPETAS VALUES('0000028','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\01. Localidad');
INSERT INTO CARPETAS VALUES('0000029','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\02. Fachada IIBB ');
INSERT INTO CARPETAS VALUES('0000030','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\03. Equipamiento instalado');
INSERT INTO CARPETAS VALUES('0000031','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\04. Equipamiento de transmisión');
INSERT INTO CARPETAS VALUES('0000032','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\05. Energía');
INSERT INTO CARPETAS VALUES('0000033','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\06. Beneficiario');
INSERT INTO CARPETAS VALUES('0000034','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\07. Módulos de acceso a internet');
INSERT INTO CARPETAS VALUES('0000035','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\08. Sistema de puesta a tierra');
INSERT INTO CARPETAS VALUES('0000036','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\09. Mediciones puesta a tierra');
INSERT INTO CARPETAS VALUES('0000037','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\10. Características del enlace');
INSERT INTO CARPETAS VALUES('0000038','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\11. Conectividad a la red');
INSERT INTO CARPETAS VALUES('0000039','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\12.Pantallas de configuración');
INSERT INTO CARPETAS VALUES('0000040','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\13. Series de equipos');
INSERT INTO CARPETAS VALUES('0000041','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\14.Anexo de Instalación de pozos');
INSERT INTO CARPETAS VALUES('0000042','\CS01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\15.Anexo prueba DITG');
INSERT INTO CARPETAS VALUES('0000043','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\01. Localidad');
INSERT INTO CARPETAS VALUES('0000044','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\02. Fachada IIBB');
INSERT INTO CARPETAS VALUES('0000045','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\03. Equipamiento instalado');
INSERT INTO CARPETAS VALUES('0000046','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\04. Equipamiento de transmisión');
INSERT INTO CARPETAS VALUES('0000047','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\05. Energía');
INSERT INTO CARPETAS VALUES('0000048','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\06. Beneficiario');
INSERT INTO CARPETAS VALUES('0000049','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\07. Módulos de acceso a internet');
INSERT INTO CARPETAS VALUES('0000050','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\08. Sistema de puesta a tierra');
INSERT INTO CARPETAS VALUES('0000051','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\09. Mediciones puesta a tierra');
INSERT INTO CARPETAS VALUES('0000052','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\10. Características del enlace');
INSERT INTO CARPETAS VALUES('0000053','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\11. Conectividad a la red');
INSERT INTO CARPETAS VALUES('0000054','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\12.Pantallas de configuración');
INSERT INTO CARPETAS VALUES('0000055','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\13. Series de equipos');
INSERT INTO CARPETAS VALUES('0000056','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\14.Anexo de Instalación de pozos A Y B');
INSERT INTO CARPETAS VALUES('0000057','\IE01\CARPETAS DE FOTOS CAPTURAS DE PANTALLA Y VIDEO\15.Anexo prueba DITG');
INSERT INTO CARPETAS VALUES('0000058','\ESTUDIO DE CAMPO\MAPA GEOREFERENCIADO (KMZ)');
INSERT INTO CARPETAS VALUES('0000059','\ESTUDIO DE CAMPO\FOTOS\FOTO CON CARTEL CON NOMBRE DE LETRERO');
INSERT INTO CARPETAS VALUES('0000060','\ESTUDIO DE CAMPO\FOTOS\FOTO DEL CENTRO COMUNAL CON CARTEL');
INSERT INTO CARPETAS VALUES('0000061','\ESTUDIO DE CAMPO\FOTOS\FOTO DEL TERRENO DE INSTALACIÓN DE LA CASETA')
INSERT INTO CARPETAS VALUES('0000062','\ESTUDIO DE CAMPO\FOTOS\FOTO DESDE LA PLAZA CON MIRAS AL NODO CON CARTEL');
INSERT INTO CARPETAS VALUES('0000063','\ESTUDIO DE CAMPO\FOTOS\FOTO PANORÁMICA DE LA LOCALIDAD CON CARTEL');
INSERT INTO CARPETAS VALUES('0000064','\ESTUDIO DE CAMPO\FOTOS\FOTO PANORAMICA DE LA PLZA PRINCIPAL CON CARTEL');
INSERT INTO CARPETAS VALUES('0000065','\ESTUDIO DE CAMPO\FOTOS\FOTO PANORÁMICA DESDE EL NODO (360°)');
INSERT INTO CARPETAS VALUES('0000066','\ESTUDIO DE CAMPO\FOTOS\FOTOS DE OTROS LUGARES PRINCIPALES CON CARTEL')






